const mockEvents = {
  city: {
    id: 1007700,
    city: "München",
    lat: 48.14,
    lon: 11.58,
    state: "",
    country: "de",
    zip: "meetup3",
    member_count: 1257
  },
  events: [
    {
      created: 1578861910000,
      duration: 14400000,
      id: "267861110",
      name: "Zum Internationalen Frauentag: Frauen zeigen euch die Wikipedia",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1583668800000,
      local_date: "2020-03-08",
      local_time: "13:00",
      updated: 1578929459000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 6,
      venue: {
        id: 26589524,
        name: "WikiMUC Wikipedia",
        lat: 48.13136291503906,
        lon: 11.57040786743164,
        repinned: true,
        address_1: "Angertorstraße 3",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1566650171000,
        name: "WikiMUC – Wikipedia in München",
        id: 32661409,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "WikiMUC-Wikipedia-in-Munchen",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/WikiMUC-Wikipedia-in-Munchen/events/267861110/",
      description:
        "<p>Alles, was ihr immer schon über Wikipedia wissen wolltet: Was bietet die Wikipedia mir als Nutzerin? Wo steht, wer einen Artikel geschrieben hat? Wie kann ich mit den AutorInnen der Artikel in Kontakt treten? Wie kann ich einen Artikel ändern, wenn mir Fehler auffallen? Kann ich eigene Bilder hochladen? Und kann ich Bilder, die auf Wikipedia stehen, für mich selber nutzen?</p> <p>Wir treffen uns am Sonntagnachmittag im WikiMUC, um alle eure Fragen rund um die Wikipedia zu beantworten. Erfahrene Wikipedianerinnen zeigen euch, wie ihr Artikel bearbeiten oder Bilder hochladen könnt.<br/>Außerdem sprechen wir über die Wiki-Schwesterprojekte: Von der Lernplattform „Wikiversity” über den Reiseführer „Wikivoyage” bis zur Zitatensammlung „Wikiquote”: Entdeckt mit uns das Wikiversum!<br/>Das alles in gemütlicher, entspannter Atmosphäre – bei Kaffee und Kuchen.</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1582134245000,
      duration: 1209600000,
      id: "268830855",
      name: "21 Days of March Nutrition and Sport Challenge",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1583132400000,
      local_date: "2020-03-02",
      local_time: "08:00",
      updated: 1582134245000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 6,
      group: {
        created: 1499625898000,
        name: "Fitness Meetup In München",
        id: 24911491,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Fitness-Meetup-In-Munchen",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Fitness-Meetup-In-Munchen/events/268830855/",
      description:
        "<p>Hey guys,</p> <p>After the great success of our February Challenge, we are keeping the momentum going and starting March with another great challenge. It begins on the 2nd of March . We‘re going to eat healthy nutrition, do some sport and feel fantastic.</p> <p>- Daily nutrition challenges<br/>- Daily exercise challenges<br/>- Extra Cooking &amp; Nutrition Education bonus Challenges<br/>- Everything can be done from your home<br/>- Personal Support &amp; guidance from your nutrition Coach</p> <p>Wana join us? Please DM me for more information</p> <p>Wish you all a great day<br/>Mark</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1581762769000,
      duration: 18000000,
      id: "268728998",
      name: "Portrait Photography I",
      rsvp_limit: 15,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1582966800000,
      local_date: "2020-02-29",
      local_time: "10:00",
      updated: 1581765372000,
      utc_offset: 3600000,
      waitlist_count: 1,
      yes_rsvp_count: 15,
      venue: {
        id: 26862593,
        name: "Gotteszeller Str. 18A",
        lat: 48.12567901611328,
        lon: 11.614749908447266,
        repinned: true,
        address_1: "Gotteszeller Str. 18A",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1500930561000,
        name: "Photography Workshops Munich",
        id: 25119735,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Munchen-Photography-Workshops",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Munchen-Photography-Workshops/events/268728998/",
      description:
        "<p>Hallo, sei herzlich Eingeladen zu meinem Fotokurs zum Thema Portrait Photography.<br/>Im Seminarraum starten wir mit einem Theorieteil zum Thema Kameraeinstellungen. Du lernst fotogene Posen für bessere Urlaubsfotos und Modelfotografie zu entwickeln. Dafür werden wir uns in der Gruppe fotografieren und es steht ein Model zur Verfügung.<br/>Ein weiterer Schwerpunkt des Tages ist der wertschätzende Umgang mit dem Foto-Motiv. Im Outdoor Teil werden wir verschiedene Orte am Ostbahnhof/Werksviertel besuchen. Dabei benutzen wir Available Light. Bei dem abschließenden Feedbackgespräch betrachten wir die Details der Fotos.</p> <p>In dem Fotoworkshop lernst Du den Einstieg in die Porträtfotografie:</p> <p>• Der richtige Umgang mit einem Model/Motiv<br/>• Bildkomposition für spannende Portraits<br/>• Tipps und Tricks für Portraits im Urlaub<br/>• Innen- und Outdoorteil<br/>• Redewendungen zum Ansprechen von unbekannten Menschen<br/>• Bildbesprechung</p> <p>Treffpunkt:[masked] um 10Uhr Gotteszeller Str. 18A, 81671 München (beim Ostbahnhof)<br/>Kurssprache: deutsch<br/>Material: Kamera, Empfehlung Objektiv zwischen 50 bis 100mm, bitte keine Teleobjektive.<br/>Teilnehmer: max. 15 Personen<br/>Kosten: 35EUR<br/>Ende: 15Uhr</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1581920270000,
      duration: 5400000,
      id: "268768551",
      name: "Exhibition visit & artist discussion",
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1583425800000,
      local_date: "2020-03-05",
      local_time: "17:30",
      updated: 1582091715000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 10,
      venue: {
        id: 26865032,
        name: "Schellingstraße 139",
        lat: 48.154117584228516,
        lon: 11.561885833740234,
        repinned: true,
        address_1: "Schellingstraße 139",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1500930561000,
        name: "Photography Workshops Munich",
        id: 25119735,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Munchen-Photography-Workshops",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Munchen-Photography-Workshops/events/268768551/",
      description:
        '<p>Steps, uncovered is a photography exhibition about dancers exploring deep emotions and becoming authentically themselves.<br/>The gallery has extended it through March 20th and I will be hosting a couple "Artist Evenings" where people can view the work and I will hold a short talk and answer questions.</p> ',
      how_to_find_us:
        "Architecktsbüro Heyne+Mayer - look for the exhibition banner, you cannot miss it.",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1557417432000,
      duration: 3600000,
      id: "hpwxxqybcdbhc",
      name: "Outdoor Training [Natural Movement]",
      rsvp_limit: 5,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1582655400000,
      local_date: "2020-02-25",
      local_time: "19:30",
      rsvp_close_offset: "PT3H",
      updated: 1557417432000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 26215358,
        name: "Westpark",
        lat: 48.12034225463867,
        lon: 11.511041641235352,
        repinned: true,
        address_1: "Specklinplatz",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1551533080000,
        name: "MovNat München [Natural Movement Fitness]",
        id: 31289377,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "MovNat-Munchen-Natural-Movement-Fitness",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/MovNat-Munchen-Natural-Movement-Fitness/events/hpwxxqybcdbhc/",
      description:
        '<p>Unser Dienstagstraining im Westpark</p> <p>Zweite Trainingseinheit 19:30 bis 20:30 Uhr</p> <p>Ein Probetraining ist kostenlos. Bitte kontaktiere uns auf jeden Fall vorher bis spätestens 16:30 Uhr am gleichen Tag per E-Mail wenn du kommen möchtest falls es einen spontanen Wechsel des Treffpunkts gibt.</p> <p>Wir freuen uns auf dich!</p> <p>Alle weiteren Trainings:<br/>5er-Karte: 70,-€ / 10er-Karte: 120,-€<br/>3-Monatskarte: 70,-€/Monat<br/>6- Monatskarte: 60,-€/Monat</p> <p><a href="http://www.movnatmuenchen.de" class="linkified">http://www.movnatmuenchen.de</a> --- [masked]</p> ',
      how_to_find_us: "Schreibe uns für den genauen Treffpunkt",
      visibility: "public",
      member_pay_fee: false
    },
    {
      local_time: "19:00",
      local_date: "2020-02-24",
      link:
        "https://www.meetup.com/munich-english-yoga-meetup/events/268650983/",
      visibility: "public_limited",
      group: {
        created: 1562661524000,
        name: "Munich English Yoga Meetup I Affordable | City center",
        id: 32349747,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "munich-english-yoga-meetup",
        who: "Munich Yogis",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      waitlist_count: 0,
      yes_rsvp_count: 5,
      duration: 3600000,
      time: 1582567200000,
      utc_offset: 3600000,
      name: "Yoga x Awa Hotel (near HBF)",
      id: "268650983"
    },
    {
      created: 1582042414000,
      duration: 3600000,
      id: "268801280",
      name: "Salsation®️ class ",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1583859600000,
      local_date: "2020-03-10",
      local_time: "18:00",
      updated: 1582095035000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 9,
      venue: {
        id: 26867318,
        name: "Tanzstudio Rebecca",
        lat: 48.096771240234375,
        lon: 11.513542175292969,
        repinned: false,
        address_1: "Machtlfingerstrasse 10",
        address_2: "(U3 Machtlfingerstrasse)",
        city: "München ",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1581673105000,
        name: "Salsation®️ Regular Class (Dance Fitness)",
        id: 33344480,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Salsation-️-Regular-Class",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Salsation-%EF%B8%8F-Regular-Class/events/268801280/",
      description:
        "<p>Hey People let’s start this Salsation®️course! 🎉<br/>.<br/>Salsation®️ is a dynamic dance fitness program that brings so much fun! It concentrates on musicality, lyrical expression and functional body movements. In one hour we will dance to different styles of music, like Reggaetón, Salsa, Merengue, Hip Hop, Dancehall and more.<br/>Just try it yourself and explore a new kind of dance workout!<br/>.<br/>Salsation®️ ist ein dynamisches Tanzfitnessprogramm, das einfach Spaß macht! Der Fokus liegt auf der Musikalität, der Interpretation der Lyrics, kombiniert mit funktionellen Bewegungen. Eine Stunde lang werden wir zu verschiedenen Musikstilen tanzen und zusammen Spaß haben: Reggaetón, Salsa, Merengue, Hip Hop, Dancehall und viele mehr.<br/>Probier es aus und entdecke eine neue Art von Tanzfitness!<br/>.<br/>Salsation®️es una clase de baile fitness divertida y dinámica con especial enfoque en musicalidad, expresión lirica y movimientos funcionales. Durante una hora bailamos diferentes estilos de música como reguetón, salsa, merengue, hip hop, dancehall y mas. Ven y disfruta una manera diferente de baile fitness.</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      local_time: "19:00",
      local_date: "2020-03-06",
      link: "https://www.meetup.com/social-drinks-munich/events/sttnprybcfbjb/",
      visibility: "public_limited",
      group: {
        created: 1557680536000,
        name: "Social Drinks Munich - Make New Friends 😊 🍻🍷🍾🎉",
        id: 31885488,
        join_mode: "approval",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "social-drinks-munich",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      waitlist_count: 0,
      yes_rsvp_count: 3,
      duration: 21600000,
      time: 1583517600000,
      utc_offset: 3600000,
      name:
        "Social Drinks Munich - Make New Friends (FREE INTL EVENT) 😊 🍻🍾🎉",
      id: "sttnprybcfbjb"
    },
    {
      local_time: "19:30",
      local_date: "2020-02-26",
      link: "https://www.meetup.com/ShinsonHapkido/events/rbpzlqybcdbjc/",
      visibility: "public_limited",
      group: {
        created: 1462997422000,
        name: "Shinson Hapkido Munich",
        id: 19941930,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "ShinsonHapkido",
        who: "Hapkido Students",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      waitlist_count: 0,
      yes_rsvp_count: 2,
      duration: 7200000,
      time: 1582741800000,
      utc_offset: 3600000,
      name: "Shinson Hapkido Training",
      id: "rbpzlqybcdbjc"
    },
    {
      local_time: "19:30",
      local_date: "2020-03-04",
      link: "https://www.meetup.com/ShinsonHapkido/events/rbpzlqybcfbgb/",
      visibility: "public_limited",
      group: {
        created: 1462997422000,
        name: "Shinson Hapkido Munich",
        id: 19941930,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "ShinsonHapkido",
        who: "Hapkido Students",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      waitlist_count: 0,
      yes_rsvp_count: 2,
      duration: 7200000,
      time: 1583346600000,
      utc_offset: 3600000,
      name: "Shinson Hapkido Training",
      id: "rbpzlqybcfbgb"
    },
    {
      created: 1522694856000,
      duration: 10800000,
      id: "lkgknpybcfbkc",
      name: "Deutsch-Japanischer\u00ad Stammtisch",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1584727200000,
      local_date: "2020-03-20",
      local_time: "19:00",
      updated: 1581165667000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 6,
      group: {
        created: 1512221367000,
        name: "Deutsch-Japanischer Stammtisch",
        id: 26763059,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "deutsch-japanischer-stammtisch",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/deutsch-japanischer-stammtisch/events/lkgknpybcfbkc/",
      description:
        "<p>Wir treffen uns einmal im Monat zum Sprach- und Kulturaustausch. Außerdem wird ein interessanter Vortrag rund um das Thema Japan gehalten. Das genaue Thema des Vortrags wird dann noch vorher bekanntgegeben.</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1567520321000,
      duration: 5400000,
      id: "vkdphrybcdbhc",
      name: "Yoga für Männer",
      rsvp_limit: 11,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1582656300000,
      local_date: "2020-02-25",
      local_time: "19:45",
      updated: 1567520321000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      venue: {
        id: 25923646,
        name: "Fraunbergstudio",
        lat: 48.10029602050781,
        lon: 11.545408248901367,
        repinned: true,
        address_1: "Fraunbergstrasse 3",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1448483136000,
        name: "München - Yoga for the people",
        id: 19154881,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Munchen-Yoga-for-the-people",
        who: "Yogis",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Munchen-Yoga-for-the-people/events/vkdphrybcdbhc/",
      description:
        "<p>Nach langen Arbeitstagen im Büro bist Du ausgebrannt und müde. Intensiven Situationen gehst Du aus dem Weg. Du bist angespannt und fühlst Deinen Körper nicht.</p> <p>Yoga? Zu esoterisch, dafür bist Du zu männlich. Erzähl Deinen Kumpels einfach, Du gehst zum Kickboxen und nutze die Vorteile dieses jahrtausendealten Übungssystems, welches von je her von Männern praktiziert wurde :</p> <p>- Deine Gedanken sind klar<br/>- Du bist ruhig und gelassen<br/>- Du bist präsent und fokussiert<br/>- Deine Sinneswahrnehmungen sind scharf<br/>- Dein Sexleben ist intensiv<br/>- Du bist bei Dir<br/>- Dein Körper ist flexibel und stark</p> <p>Komme vorbei und überzeuge Dich selbst.</p> <p>Egal, ob Du neu bist oder schon Yoga-Erfahrung mitbringst. Zusammen üben wir Atem-, Körperübungen, Meditation und Tiefenentspannung.</p> <p>Ich unterrichte Yoga seit 8 Jahren mit großer Begeisterung.</p> <p>Yogamatten und Sitzkissen sind bereits vorhanden. Komm einfach in lockerer Sportkleidung (Jogginghose / Tshirt).</p> <p>Für Fragen : Schreib mir über meetup bzw. 01511/[masked].</p> <p>15€ p.P. / Session<br/>Schnupperpreis 10€ (für erstmalige Teilnahme)</p> <p>Ich freue mich auf Dich!</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1575706262000,
      duration: 4500000,
      id: "nvcvlrybcdbkc",
      name: "Hatha Yoga für Anfänger",
      rsvp_limit: 12,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1582828200000,
      local_date: "2020-02-27",
      local_time: "19:30",
      updated: 1575706262000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 25923646,
        name: "Fraunbergstudio",
        lat: 48.10029602050781,
        lon: 11.545408248901367,
        repinned: true,
        address_1: "Fraunbergstrasse 3",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1448483136000,
        name: "München - Yoga for the people",
        id: 19154881,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Munchen-Yoga-for-the-people",
        who: "Yogis",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Munchen-Yoga-for-the-people/events/nvcvlrybcdbkc/",
      description:
        "<p>Komme vorbei und probiere dieses jahrtausende alte indische Übungssystem selbst aus.</p> <p>Was kannst Du erwarten ?</p> <p>Hatha Yoga wird Dir dabei helfen,</p> <p>- Dich zu entspannen<br/>- wieder in Deine Mitte zu finden<br/>- körperliche und emotionale Blockaden zu lösen<br/>- Herr über Deine Gedanken zu werden<br/>- und noch vieles mehr</p> <p>FAQ :<br/>Was muss ich mitbringen ?</p> <p>- lockere Sportkleidung (zB. Jogging-/oder Legginghose und ein T-Shirt)</p> <p>Was brauche ich sonst noch ?</p> <p>- Nichts. Yogamatten / Sitzkissen etc. sind alle vorhanden.</p> <p>Muss ich schon Yoga-Erfahrung haben ?</p> <p>- Nein</p> <p>Ich bin nicht gelenkig/sportlich genug, kann ich trotzdem mitmachen ?</p> <p>- JA !</p> <p>Kosten : 15€ p.P.</p> <p>Jeden Donnerstag von 19:30-20:45 Uhr.</p> <p>Wir freuen uns auf Dich!</p> ",
      how_to_find_us: "Fraunbergstraße 3 / Nähe Thalkirchen",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1581894801000,
      duration: 9000000,
      id: "268762263",
      name: "Sharing & review of your photos",
      rsvp_limit: 24,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1583076600000,
      local_date: "2020-03-01",
      local_time: "16:30",
      updated: 1581895532000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 16,
      venue: {
        id: 26051335,
        name: "Cafe Cord",
        lat: 48.136409759521484,
        lon: 11.565984725952148,
        repinned: true,
        address_1: "Sonnenstraße 19",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1500930561000,
        name: "Photography Workshops Munich",
        id: 25119735,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Munchen-Photography-Workshops",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Munchen-Photography-Workshops/events/268762263/",
      description:
        '<p>You have probably shot some cool pictures during one of our last session like the "Portrait practice session"! Or you have some newly taken photos on your recent trip you want to share! Bring them along, and let\'s discuss in a small friendly group how they could be improved!</p> <p>It\'s a great way to get a new perspective on photos you like - and probably on those that you think didn\'t quite work out the way you planned them to be. Probably we can find a fix :)</p> <p>Do limit your choice of photos to less than five, so we can concentrate on the story you want to tell.</p> <p>You can bring the digital file with you on a tablet or laptop (Cafe Cord has no Wifi). Better yet, print them out and bring them along! It cost less than a Euro to print them at DM for example, or at your favourite photo-lab for even better color quality!</p> <p>To see other workshops in Munich, and to host events yourselves, check out also <a href="https://www.lulalearn.com/event_list/" class="linkified">https://www.lulalearn.com/event_list/</a></p> ',
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1581757702000,
      duration: 25200000,
      id: "268728339",
      name: "Lindau: 21.03.2020 Streetfotografie",
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1584781200000,
      local_date: "2020-03-21",
      local_time: "10:00",
      updated: 1581757702000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      group: {
        created: 1492940309000,
        name: "Fotografie für Anfänger und Kreative",
        id: 23387166,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Fotografie-fur-Anfanger-und-Kreative",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Fotografie-fur-Anfanger-und-Kreative/events/268728339/",
      description:
        '<p>Details:<br/>Anmeldung bitte nur über die Fujifilmseite:<br/><a href="https://www.fujifilm-shop.de/lindau-21-03-2020-streetfotografie.html" class="linkified">https://www.fujifilm-shop.de/lindau-21-03-2020-streetfotografie.html</a></p> <p>Lindau:[masked] Streetfotografie,[masked]€</p> <p>Die Streetfotografie zeigt einen Augenblick so, wie er gerade ist. Die Bilder sind authentisch, nichts wird manipuliert oder inszeniert. Sie haben einen fast dokumentarischen Charakter.</p> <p>Das Leben auf der Straße zu fotografieren, ist in der heutigen Zeit ein nicht ganz einfaches Unterfangen und stellt insbesondere Anfänger vor eine große Herausforderung. Das Geschehen beobachten, schnell reagieren und die Gelegenheit nutzen, das Erlebte in einem aussagekräftigen Bild festzuhalten.<br/>In unserem Workshop lernen Sie Techniken der Unschärfe und wie Sie Perspektive und Wischeffekte gezielt einsetzen, um Spannung, Hektik und Bewegung auszudrücken. Karsten Rose zeigt Ihnen außerdem, wie Sie auf fremde Passanten zugehen und mit ihnen Kontakt aufnehmen.<br/>Kommen Sie mit auf diesen spannenden Fotowalk!</p> <p>Themen:</p> <p>Grundlagen der Streetfotografie<br/>Belichtungszeit &amp; Blende<br/>Autofokus / manuelle Scharfstellung<br/>Brennweite<br/>Schärfe &amp; Schärfentiefe<br/>Bewegungsunschärfe<br/>ISO Empfindlichkeit<br/>Perspektive<br/>Aufnahmestandpunkt<br/>Datenschutz</p> <p>Zielgruppe:<br/>Geeignet für Fortgeschrittene, die neue Sichtweisen und Techniken der Streetfotografie kennenlernen wollen. Wichtig ist, dass Sie die Kamerafunktionen Blenden- und Zeitautomatik kennen und Ihnen die wichtigsten Menüfunktionen bekannt sind.<br/>Wenn Sie sich nicht sicher sind, ob das der richtige Workshop für Sie ist, schreiben Sie uns gerne an [masked].</p> <p>Ausrüstung:<br/>Ihre Kamera sollte die Möglichkeit bieten, Zeit und Blende manuell einzustellen. Wechselobjektive sind nicht nötig. Bitte denken Sie an einen vollgeladenen Akku und die Bedienungsanleitung Ihrer Kamera.</p> <p>Auf Wunsch stellen wir ihnen FUJIFILM Leihkameras und Objektive der X Serie zur Verfügung. Bitte geben Sie dies bei der Anmeldung an!</p> <p>Kosten und Leistungen:<br/>Wir bieten Ihnen während des gesamten Workshops die professionelle Betreuung jedes Einzelnen sowie Verpflegung. Außerdem erhält jeder Teilnehmer ein Teilnahmezertifikat über das erfolgreiche Erreichen des Workshop-Ziels.</p> <p>Dozent: Karsten Rose<br/>Dauer: 7 Stunden<br/>Preis: 129,00 €<br/>Teilnehmer: Minimal: 3 | Maximal: 10</p> <p>Termin und Treffpunkt:</p> <p>[masked] | 10:00 – 17:00 Uhr<br/>Mang Turm | Hafenplatz | 88131 Lindau (Bodensee)<br/>Parkmöglichkeiten: Parkhaus am Hauptbahnhof Lindau</p> <p>Anmeldung bitte nur über die Fujifilmseite:<br/><a href="https://www.fujifilm-shop.de/lindau-21-03-2020-streetfotografie.html" class="linkified">https://www.fujifilm-shop.de/lindau-21-03-2020-streetfotografie.html</a></p> ',
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1582042666000,
      duration: 3600000,
      id: "268801375",
      name: "Salsation®️ class ",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1584464400000,
      local_date: "2020-03-17",
      local_time: "18:00",
      updated: 1582095062000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      group: {
        created: 1581673105000,
        name: "Salsation®️ Regular Class (Dance Fitness)",
        id: 33344480,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Salsation-️-Regular-Class",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Salsation-%EF%B8%8F-Regular-Class/events/268801375/",
      description:
        "<p>Hey People let’s start this Salsation®️course! 🎉</p> <p>As the entrance is free I would be blessed if you leave a contribution for the rent of the room. 🙃</p> <p>Salsation®️ is a dynamic dance fitness program that brings so much fun! It concentrates on musicality, lyrical expression and functional body movements. In one hour we will dance to different styles of music, like Reggaetón, Salsa, Merengue, Hip Hop, Dancehall and more.<br/>Just try it yourself and explore a new kind of dance workout!<br/>.<br/>Salsation®️ ist ein dynamisches Tanzfitnessprogramm, das einfach Spaß macht! Der Fokus liegt auf der Musikalität, der Interpretation der Lyrics, kombiniert mit funktionellen Bewegungen. Eine Stunde lang werden wir zu verschiedenen Musikstilen tanzen und zusammen Spaß haben: Reggaetón, Salsa, Merengue, Hip Hop, Dancehall und viele mehr.<br/>Probier es aus und entdecke eine neue Art von Tanzfitness!<br/>.<br/>Salsation®️es una clase de baile fitness divertida y dinámica con especial enfoque en musicalidad, expresión lirica y movimientos funcionales. Durante una hora bailamos diferentes estilos de música como reguetón, salsa, merengue, hip hop, dancehall y mas. Ven y disfruta una manera diferente de baile fitness.</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1582042812000,
      duration: 3600000,
      id: "268801437",
      name: "Salsation®️ class ",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1585670400000,
      local_date: "2020-03-31",
      local_time: "18:00",
      updated: 1582095100000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      group: {
        created: 1581673105000,
        name: "Salsation®️ Regular Class (Dance Fitness)",
        id: 33344480,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Salsation-️-Regular-Class",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Salsation-%EF%B8%8F-Regular-Class/events/268801437/",
      description:
        "<p>Hey People let’s start this Salsation®️course! 🎉</p> <p>As the entrance is free I would be blessed if you leave a contribution for the rent of the room. 🙃</p> <p>Salsation®️ is a dynamic dance fitness program that brings so much fun! It concentrates on musicality, lyrical expression and functional body movements. In one hour we will dance to different styles of music, like Reggaetón, Salsa, Merengue, Hip Hop, Dancehall and more.<br/>Just try it yourself and explore a new kind of dance workout!<br/>.<br/>Salsation®️ ist ein dynamisches Tanzfitnessprogramm, das einfach Spaß macht! Der Fokus liegt auf der Musikalität, der Interpretation der Lyrics, kombiniert mit funktionellen Bewegungen. Eine Stunde lang werden wir zu verschiedenen Musikstilen tanzen und zusammen Spaß haben: Reggaetón, Salsa, Merengue, Hip Hop, Dancehall und viele mehr.<br/>Probier es aus und entdecke eine neue Art von Tanzfitness!<br/>.<br/>Salsation®️es una clase de baile fitness divertida y dinámica con especial enfoque en musicalidad, expresión lirica y movimientos funcionales. Durante una hora bailamos diferentes estilos de música como reguetón, salsa, merengue, hip hop, dancehall y mas. Ven y disfruta una manera diferente de baile fitness.</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1581757955000,
      duration: 25200000,
      id: "268728377",
      name: "Konstanz: 25.04.2020 Streetfotografie",
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1587801600000,
      local_date: "2020-04-25",
      local_time: "10:00",
      updated: 1581757955000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      group: {
        created: 1492940309000,
        name: "Fotografie für Anfänger und Kreative",
        id: 23387166,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Fotografie-fur-Anfanger-und-Kreative",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Fotografie-fur-Anfanger-und-Kreative/events/268728377/",
      description:
        '<p>Details</p> <p>Details:<br/>Anmeldung bitte nur über die Fujifilmseite:<br/><a href="https://www.fujifilm-shop.de/konstanz-25-04-2020-streetfotografie.html" class="linkified">https://www.fujifilm-shop.de/konstanz-25-04-2020-streetfotografie.html</a></p> <p>Lindau:[masked] Streetfotografie,[masked]€</p> <p>Die Streetfotografie zeigt einen Augenblick so, wie er gerade ist. Die Bilder sind authentisch, nichts wird manipuliert oder inszeniert. Sie haben einen fast dokumentarischen Charakter.</p> <p>Das Leben auf der Straße zu fotografieren, ist in der heutigen Zeit ein nicht ganz einfaches Unterfangen und stellt insbesondere Anfänger vor eine große Herausforderung. Das Geschehen beobachten, schnell reagieren und die Gelegenheit nutzen, das Erlebte in einem aussagekräftigen Bild festzuhalten.<br/>In unserem Workshop lernen Sie Techniken der Unschärfe und wie Sie Perspektive und Wischeffekte gezielt einsetzen, um Spannung, Hektik und Bewegung auszudrücken. Karsten Rose zeigt Ihnen außerdem, wie Sie auf fremde Passanten zugehen und mit ihnen Kontakt aufnehmen.<br/>Kommen Sie mit auf diesen spannenden Fotowalk!</p> <p>Themen:</p> <p>Grundlagen der Streetfotografie<br/>Belichtungszeit &amp; Blende<br/>Autofokus / manuelle Scharfstellung<br/>Brennweite<br/>Schärfe &amp; Schärfentiefe<br/>Bewegungsunschärfe<br/>ISO Empfindlichkeit<br/>Perspektive<br/>Aufnahmestandpunkt<br/>Datenschutz</p> <p>Zielgruppe:<br/>Geeignet für Fortgeschrittene, die neue Sichtweisen und Techniken der Streetfotografie kennenlernen wollen. Wichtig ist, dass Sie die Kamerafunktionen Blenden- und Zeitautomatik kennen und Ihnen die wichtigsten Menüfunktionen bekannt sind.<br/>Wenn Sie sich nicht sicher sind, ob das der richtige Workshop für Sie ist, schreiben Sie uns gerne an [masked].</p> <p>Ausrüstung:<br/>Ihre Kamera sollte die Möglichkeit bieten, Zeit und Blende manuell einzustellen. Wechselobjektive sind nicht nötig. Bitte denken Sie an einen vollgeladenen Akku und die Bedienungsanleitung Ihrer Kamera.</p> <p>Auf Wunsch stellen wir ihnen FUJIFILM Leihkameras und Objektive der X Serie zur Verfügung. Bitte geben Sie dies bei der Anmeldung an!</p> <p>Kosten und Leistungen:<br/>Wir bieten Ihnen während des gesamten Workshops die professionelle Betreuung jedes Einzelnen sowie Verpflegung. Außerdem erhält jeder Teilnehmer ein Teilnahmezertifikat über das erfolgreiche Erreichen des Workshop-Ziels.</p> <p>Dozent: Karsten Rose<br/>Dauer: 7 Stunden<br/>Preis: 129,00 €<br/>Teilnehmer: Minimal: 3 | Maximal: 10</p> <p>Termin und Treffpunkt:</p> <p>[masked] | 10:00 – 17:00 Uhr<br/>Mang Turm | Hafenplatz | 88131 Lindau (Bodensee)<br/>Parkmöglichkeiten: Parkhaus am Hauptbahnhof Lindau</p> <p>Anmeldung bitte nur über die Fujifilmseite:<br/><a href="https://www.fujifilm-shop.de/konstanz-25-04-2020-streetfotografie.html" class="linkified">https://www.fujifilm-shop.de/konstanz-25-04-2020-streetfotografie.html</a></p> ',
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1557417224000,
      duration: 3600000,
      id: "tlwxxqybcdbhc",
      name: "Outdoor Training [Natural Movement]",
      rsvp_limit: 5,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1582651800000,
      local_date: "2020-02-25",
      local_time: "18:30",
      rsvp_close_offset: "PT2H",
      updated: 1557417224000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 26215358,
        name: "Westpark",
        lat: 48.12034225463867,
        lon: 11.511041641235352,
        repinned: true,
        address_1: "Specklinplatz",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1551533080000,
        name: "MovNat München [Natural Movement Fitness]",
        id: 31289377,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "MovNat-Munchen-Natural-Movement-Fitness",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/MovNat-Munchen-Natural-Movement-Fitness/events/tlwxxqybcdbhc/",
      description:
        '<p>Unser Dienstagstraining im Westpark</p> <p>Erste Trainingseinheit 18:30 bis 19:30 Uhr</p> <p>Ein Probetraining ist kostenlos. Bitte kontaktiere uns auf jeden Fall vorher bis spätestens 16:30 Uhr am gleichen Tag per E-Mail wenn du kommen möchtest falls es einen spontanen Wechsel des Treffpunkts gibt.</p> <p>Wir freuen uns auf dich!</p> <p>Alle weiteren Trainings:<br/>5er-Karte: 70,-€ / 10er-Karte: 120,-€<br/>3-Monatskarte: 70,-€/Monat<br/>6- Monatskarte: 60,-€/Monat</p> <p><a href="http://www.movnatmuenchen.de" class="linkified">http://www.movnatmuenchen.de</a> --- [masked]</p> ',
      how_to_find_us: "Schreibe uns für den genauen Treffpunkt",
      visibility: "public",
      member_pay_fee: false
    },
    {
      local_time: "19:00",
      local_date: "2020-02-28",
      link: "https://www.meetup.com/social-drinks-munich/events/sttnprybcdblc/",
      visibility: "public_limited",
      group: {
        created: 1557680536000,
        name: "Social Drinks Munich - Make New Friends 😊 🍻🍷🍾🎉",
        id: 31885488,
        join_mode: "approval",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "social-drinks-munich",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      waitlist_count: 0,
      yes_rsvp_count: 2,
      duration: 21600000,
      time: 1582912800000,
      utc_offset: 3600000,
      name:
        "Social Drinks Munich - Make New Friends (FREE INTL EVENT) 😊 🍻🍾🎉",
      id: "sttnprybcdblc"
    }
  ]
};

export { mockEvents };
